# Generated by Django 4.2.30 on 2026-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Público'), ('INTERNAL_ONLY', 'Apenas Interno'), ('MANAGERS_ONLY', 'Apenas Gestores')], default='PUBLIC', max_length=20),
        ),
    ]
