# Generated by Django 4.2.30 on 2026-06-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_favoritearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#14B8A6', max_length=7)),
                ('require_2fa', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=120)),
                ('slack_webhook_url', models.URLField(blank=True, null=True)),
                ('force_dark_mode', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='wiki.company')),
            ],
        ),
    ]
