# Generated by Django 4.2.30 on 2026-06-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_workspacesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesettings',
            name='border_style',
            field=models.CharField(choices=[('SHARP', '0px'), ('ROUNDED', '8px'), ('PILL', '9999px')], default='ROUNDED', max_length=15),
        ),
        migrations.AddField(
            model_name='workspacesettings',
            name='compact_layout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
        migrations.AddField(
            model_name='workspacesettings',
            name='font_family',
            field=models.CharField(choices=[('MODERN', 'Inter, sans-serif'), ('CLASSIC', 'Merriweather, serif'), ('TECHNICAL', 'Fira Code, monospace')], default='MODERN', max_length=20),
        ),
    ]
