# Generated by Django 4.2.30 on 2026-06-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_workspacesettings_border_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacesettings',
            name='force_dark_mode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(choices=[('ENTERPRISE', 'Enterprise Blue'), ('SLATE', 'Slate Minimalist'), ('CYBER', 'Cyber/Synthwave'), ('NORDIC', 'Nordic Forest'), ('CONTRAST', 'High-Contrast')], default='ENTERPRISE', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='wiki.company'),
        ),
    ]
