# Generated by Django 4.2.30 on 2026-06-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_remove_workspacesettings_force_dark_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='theme_preference',
        ),
        migrations.AddField(
            model_name='workspacesettings',
            name='theme_preference',
            field=models.CharField(choices=[('ENTERPRISE', 'Enterprise Blue'), ('SLATE', 'Slate Minimalist'), ('CYBER', 'Cyber/Synthwave'), ('NORDIC', 'Nordic Forest'), ('CONTRAST', 'High-Contrast')], default='ENTERPRISE', max_length=20),
        ),
    ]
