# Generated by Django 4.2.30 on 2026-06-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_remove_customuser_theme_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesettings',
            name='force_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workspacesettings',
            name='theme_preference',
            field=models.CharField(choices=[('ENTERPRISE', 'Enterprise Blue'), ('SLATE', 'Slate Minimalist'), ('NORDIC', 'Nordic Forest')], default='ENTERPRISE', max_length=20),
        ),
    ]
