# Generated by Django 4.2.30 on 2026-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_workspacesettings_force_dark_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacesettings',
            name='force_dark_mode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
