# Generated by Django 4.2.30 on 2026-06-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_remove_workspacesettings_force_dark_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesettings',
            name='theme_preference',
            field=models.CharField(choices=[('ENTERPRISE', 'Enterprise Blue'), ('SLATE', 'Slate Minimalist'), ('NORDIC', 'Nordic Forest'), ('SNOW', 'Branco Neve (Minimalista)'), ('PEARL', 'Branco Pérola (Quente)'), ('SILVER', 'Branco Prata (Frio)')], default='ENTERPRISE', max_length=20),
        ),
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_html', models.TextField(blank=True)),
                ('default_tags', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=255)),
                ('default_visibility', models.CharField(choices=[('PUBLIC', 'Público'), ('INTERNAL_ONLY', 'Apenas Interno'), ('MANAGERS_ONLY', 'Apenas Gestores')], default='PUBLIC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_templates', to='wiki.company')),
            ],
        ),
    ]
