# Generated by Django 4.2.30 on 2026-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_alter_workspacesettings_theme_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacesettings',
            name='border_style',
        ),
        migrations.RemoveField(
            model_name='workspacesettings',
            name='compact_layout',
        ),
        migrations.RemoveField(
            model_name='workspacesettings',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='workspacesettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='workspacesettings',
            name='theme_preference',
        ),
        migrations.AddField(
            model_name='customuser',
            name='border_style',
            field=models.CharField(choices=[('SHARP', '0px'), ('ROUNDED', '8px'), ('PILL', '9999px')], default='ROUNDED', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='compact_layout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='font_family',
            field=models.CharField(choices=[('MODERN', 'Inter, sans-serif'), ('CLASSIC', 'Merriweather, serif'), ('TECHNICAL', 'Fira Code, monospace')], default='MODERN', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='primary_color',
            field=models.CharField(default='#14B8A6', max_length=7),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(choices=[('ENTERPRISE', 'Enterprise Blue'), ('SLATE', 'Slate Minimalist'), ('NORDIC', 'Nordic Forest'), ('SNOW', 'Branco Neve (Minimalista)'), ('PEARL', 'Branco Pérola (Quente)'), ('SILVER', 'Branco Prata (Frio)')], default='ENTERPRISE', max_length=20),
        ),
    ]
