# Generated by Django 4.2.30 on 2026-06-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_eventtype_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
