# Generated by Django 4.2.30 on 2026-06-17 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_article_attachment_size_article_cover_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='articletemplate',
            name='default_tags',
        ),
        migrations.AddField(
            model_name='articletemplate',
            name='default_tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='wiki.tag'),
        ),
    ]
