# Generated by Django 4.2.30 on 2026-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_userpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('COMMON', 'Usuário'), ('EMPLOYEE', 'Funcionário'), ('ADMIN', 'Supervisor'), ('SUPERADMIN', 'Superadmin')], default='COMMON', max_length=20),
        ),
    ]
