from django.urls import path
from .views import (
    HomeView, ArticleDetailView, CategoryDetailView, SearchView, 
    CustomLoginView, CustomLogoutView, GatewayView, ExitCompanyView,
    ArticleFrontendCreateView, ArticleReviewView, NotificationsAPIView,
    CategoryCreateAPIView, UserProfileView, SettingsView, UserCreateAPIView, ArticleFrontendUpdateView,
    FavoriteToggleAPIView, ToggleDarkModeAPIView, TemplateDataAPIView,
    FullCalendarView, EventsAPIView, EventCreateAPIView, EventTypeCreateAPIView,
    MasterLoginView, MasterDashboardView, UserHistoryAPIView, ApproveArticleAPIView, HeartbeatAPIView
)

urlpatterns = [
    path('acesso/', GatewayView.as_view(), name='gateway'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('sair-empresa/', ExitCompanyView.as_view(), name='exit_company'),
    path('master-control-panel/', MasterDashboardView.as_view(), name='master_dashboard'),
    path('master-control-panel/login/', MasterLoginView.as_view(), name='master_login'),
    path('perfil/', UserProfileView.as_view(), name='profile'),
    path('configuracoes/', SettingsView.as_view(), name='settings'),
    path('artigos/novo/', ArticleFrontendCreateView.as_view(), name='article_create'),
    path('artigo/<slug:slug>/editar/', ArticleFrontendUpdateView.as_view(), name='article_update'),
    path('artigo/<slug:slug>/revisar/', ArticleReviewView.as_view(), name='article_review'),
    path('artigo/<slug:slug>/favoritar/', FavoriteToggleAPIView.as_view(), name='api_favorite_toggle'),
    path('api/notifications/', NotificationsAPIView.as_view(), name='api_notifications'),
    path('api/categories/novo/', CategoryCreateAPIView.as_view(), name='api_category_create'),
    path('api/users/novo/', UserCreateAPIView.as_view(), name='api_user_create'),
    path('api/users/<int:user_id>/history/', UserHistoryAPIView.as_view(), name='api_user_history'),
    path('api/heartbeat/', HeartbeatAPIView.as_view(), name='api_heartbeat'),
    path('api/articles/<int:article_id>/approve/', ApproveArticleAPIView.as_view(), name='api_article_approve'),
    path('api/toggle-dark-mode/', ToggleDarkModeAPIView.as_view(), name='api_toggle_dark_mode'),
    path('api/templates/<int:template_id>/', TemplateDataAPIView.as_view(), name='api_template_data'),
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path('calendario/', FullCalendarView.as_view(), name='calendar'),
    path('api/events/', EventsAPIView.as_view(), name='api_events'),
    path('api/events/create/', EventCreateAPIView.as_view(), name='api_events_create'),
    path('api/events/types/create/', EventTypeCreateAPIView.as_view(), name='api_event_types_create'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('artigo/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
]
